<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TO8K4MZL2-D" name="com.fanniemae.WorkFlowManagement" tests="1" failures="0" timestamp="2020-01-11T12:16:45 IST" time="66.981" errors="1">
  <testcase name="workflowMgnt" time="66.981" classname="com.fanniemae.WorkFlowManagement">
    <error type="com.techouts.fanniemae.exceptions.FannieMaeBusinessException" message="throwing exception to make sure capturing testcase result to testNG">
      <![CDATA[com.techouts.fanniemae.exceptions.FannieMaeBusinessException: throwing exception to make sure capturing testcase result to testNG
at com.fanniemae.automation.test.AbstractTest.performPostExceptionProcess(AbstractTest.java:244)
at com.fanniemae.WorkFlowManagement.workflowMgnt(WorkFlowManagement.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.techouts.fanniemae.exceptions.FannieMaeBusinessException: throwing exception to make sure capturing testcase result to testNG
at com.fanniemae.automation.test.AbstractTest.performPostExceptionProcess(AbstractTest.java:242)
... 29 more
Caused by: com.techouts.fanniemae.exceptions.FannieMaeBusinessException: unable to perform logout operation in TestCase[WorkFlowManagement].
at com.fanniemae.automation.test.page.actions.HomePageActions.logout(HomePageActions.java:310)
at com.fanniemae.WorkFlowManagement.workflowMgnt(WorkFlowManagement.java:53)
... 28 more
]]>
    </error>
  </testcase> <!-- workflowMgnt -->
</testsuite> <!-- com.fanniemae.WorkFlowManagement -->
